CREATE DATABASE INEURON_SQL_PROJECT;
USE INEURON_SQL_PROJECT;


-- TASK 1
CREATE TABLE SHOPPING_HISTORY (
  PRODUCT VARCHAR(10) NOT NULL,
  QUANTITY INT NOT NULL,
  UNIT_PRICE INT NOT NULL
);

INSERT INTO SHOPPING_HISTORY VALUES
('MILK',2,10),
('BREAD',5,10),
('EGG',12,6),
('BREAD',2,15),
('MAGGI',10,12),
('MILK',5,30),
('EGG',10,5),
('COFFEE',20,10),
('MILK',5,15),
('TEA',10,7);

SELECT * FROM SHOPPING_HISTORY;

SELECT PRODUCT, 
       SUM(QUANTITY * UNIT_PRICE) AS TOTAL_PRICE
FROM SHOPPING_HISTORY
GROUP BY PRODUCT;